DEFINE OUTPUT PARAMETER opcVersion AS CHARACTER NO-UNDO.

PROCEDURE zmq_version EXTERNAL "vendor/2.2.0/windows_32/libzmq.dll" CDECL:
  DEFINE INPUT-OUTPUT PARAMETER major AS LONG NO-UNDO.
  DEFINE INPUT-OUTPUT PARAMETER minor AS LONG NO-UNDO.
  DEFINE INPUT-OUTPUT PARAMETER patch AS LONG NO-UNDO.
END PROCEDURE.

DEFINE VARIABLE iMajor AS INTEGER NO-UNDO.
DEFINE VARIABLE iMinor AS INTEGER NO-UNDO.
DEFINE VARIABLE iPatch AS INTEGER NO-UNDO.

RUN zmq_version(INPUT-OUTPUT iMajor,
                INPUT-OUTPUT iMinor,
                INPUT-OUTPUT iPatch).

ASSIGN opcVersion = SUBSTITUTE("&1.&2.&3", iMajor, iMinor, iPatch).
