DEFINE OUTPUT PARAMETER opiVersion AS INTEGER EXTENT 3 NO-UNDO.

RUN zmq_version(INPUT-OUTPUT opiVersion[1],
                INPUT-OUTPUT opiVersion[2],
                INPUT-OUTPUT opiVersion[3]).

PROCEDURE zmq_version EXTERNAL "vendor/2.2.0/windows_32/libzmq.dll" CDECL:
  DEFINE INPUT-OUTPUT PARAMETER major AS LONG NO-UNDO.
  DEFINE INPUT-OUTPUT PARAMETER minor AS LONG NO-UNDO.
  DEFINE INPUT-OUTPUT PARAMETER patch AS LONG NO-UNDO.
END PROCEDURE.
